# Generated by Django 3.1.4 on 2021-01-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(blank=True, db_column='content', max_length=1000, null=True, verbose_name='comment')),
                ('written', models.DateTimeField(auto_now_add=True, db_column='written')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified')),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(blank=True, db_column='text', max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modified')),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('path', models.CharField(db_column='path', max_length=100, verbose_name='path_to_img')),
            ],
            options={
                'db_table': 'postimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('like', models.IntegerField(blank=True, db_column='like', null=True, verbose_name='like')),
                ('love', models.IntegerField(blank=True, db_column='love', null=True, verbose_name='love')),
                ('care', models.IntegerField(blank=True, db_column='care', null=True, verbose_name='care')),
                ('haha', models.IntegerField(blank=True, db_column='haha', null=True, verbose_name='haha')),
                ('sad', models.IntegerField(blank=True, db_column='sad', null=True, verbose_name='sad')),
                ('angry', models.IntegerField(blank=True, db_column='angry', null=True, verbose_name='angry')),
            ],
            options={
                'db_table': 'reaction',
                'managed': False,
            },
        ),
    ]
