# Generated by Django 3.1.4 on 2021-01-27 11:37

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(db_column='image', max_length=255, null=True, upload_to=post.models.image_upload_location)),
            ],
            options={
                'db_table': 'postimage',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
