# Generated by Django 3.1.4 on 2021-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210127_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'post_images',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
