# Generated by Django 3.1.4 on 2021-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210127_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendTaggedInPost',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('tagged_at', models.DateTimeField(auto_now_add=True, db_column='tagged')),
            ],
            options={
                'db_table': 'friendtaggedinpost',
                'managed': False,
            },
        ),
    ]
