# Generated by Django 3.1.4 on 2021-01-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostNotification',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(db_column='action', max_length=1000)),
                ('notified', models.DateTimeField(auto_now_add=True, db_column='notified')),
            ],
            options={
                'db_table': 'postnotification',
                'managed': False,
            },
        ),
    ]
