# Generated by Django 3.1.4 on 2021-02-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_groupadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinGroupRequest',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('sent', models.DateTimeField(auto_now_add=True, db_column='sent')),
            ],
            options={
                'db_table': 'joingrouprequest',
                'managed': False,
            },
        ),
    ]
