# Generated by Django 3.1.4 on 2021-02-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_joingrouprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJoinInvitation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('invited', models.DateTimeField(auto_now_add=True, db_column='invited')),
            ],
            options={
                'db_table': 'groupjoininvitation',
                'managed': False,
            },
        ),
    ]
