# Generated by Django 3.1.4 on 2021-01-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('name', models.CharField(db_column='name', default='', max_length=45, verbose_name='name')),
            ],
            options={
                'db_table': 'chatbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(db_column='content', verbose_name='content')),
                ('sent', models.DateTimeField(auto_now_add=True, db_column='sent')),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
    ]
