# Generated by Django 3.1.4 on 2021-01-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatBox',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('name', models.CharField(db_column='name', max_length=45, verbose_name='name')),
            ],
            options={
                'db_table': 'groupchatbox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(db_column='content', verbose_name='content')),
                ('sent', models.DateTimeField(auto_now_add=True, db_column='sent')),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
    ]
