# Generated by Django 3.1.4 on 2021-01-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupchatbox_groupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinGroupChat',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'joingroupchat',
                'managed': False,
            },
        ),
    ]
