# Generated by Django 3.1.4 on 2021-01-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_joingroupchat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupmessage',
            table='groupmessage',
        ),
    ]
