# Generated by Django 3.1.5 on 2021-01-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(db_column='username', max_length=20, unique=True, verbose_name='user name')),
                ('avatar', models.ImageField(db_column='avatar', upload_to='')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_admin', models.BooleanField(db_column='is_admin', default=False)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
