# Generated by Django 3.1.5 on 2021-01-21 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True, db_column='added')),
                ('user1', models.ForeignKey(db_column='user1', on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='user2', on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('sended', models.DateTimeField(auto_now_add=True, db_column='sended')),
                ('status', models.IntegerField(choices=[('IDLE', 0), ('ACCEPTED', 1), ('REJECTED', 2)], db_column='status', default='IDLE', verbose_name='status')),
                ('receiver', models.ForeignKey(db_column='receiver', on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('blocked', models.DateTimeField(auto_now_add=True, db_column='blocked')),
                ('blockee', models.ForeignKey(db_column='blockee', on_delete=django.db.models.deletion.CASCADE, related_name='blockee', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(db_column='blocker', on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
