# Generated by Django 3.1.5 on 2021-01-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_block_friendrequest_friendship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'managed': False},
        ),
    ]
