# Generated by Django 3.1.5 on 2021-01-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210121_2239'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='block',
            table='block',
        ),
        migrations.AlterModelTable(
            name='friendrequest',
            table='friendrequest',
        ),
        migrations.AlterModelTable(
            name='friendship',
            table='friendship',
        ),
    ]
